AutoImports/AutoImports/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLogic;
using System.Web.Security;
using System.Net.Mail;
using Common;
using System.Text.RegularExpressions;

namespace ClassExample.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(string username, string password)
        {
            if (!User.Identity.IsAuthenticated)
            {
                if (new UsersOperations().Login(username, password) == true)
                {
                    //log in
                    FormsAuthentication.SetAuthCookie(username, true);
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewData["message"] = "There are no accounts with those credentials. Please check your username and password again.";
                }
            }
            return View();
        }

        public ActionResult SignOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Register()
        {
            if (User.Identity.IsAuthenticated)
            {

                FormsAuthentication.SignOut();
            }
            return RedirectToAction("Register", "Users");
        }

        public ActionResult RecoverPassword(string username, string email)
        {
            UsersOperations uo = new UsersOperations();
            try
            {
                if (uo.CheckUserEmail(username, email))
                {
                    string token = new AccountsOperations().GeneratePasswordRecoveryToken(25);
                    User u = uo.GetUser(username);
                    uo.PasswordRequest(u, token);

                    MailMessage mail = new MailMessage();
                    mail.To.Add(email);
                    mail.From = new MailAddress("autoimportsnoreply@gmail.com");
                    mail.Subject = "Forgot Password";
                    string body = "Please go to this address to recover your password /Accounts/ChangePassword/?user=" + username + "&req=" + token;
                    mail.Body = body;
                    mail.IsBodyHtml = true;
                    SmtpClient smtp = new SmtpClient();
                    smtp.Host = "smtp.gmail.com";
                    smtp.Port = 587;
                    smtp.UseDefaultCredentials = false;
                    smtp.EnableSsl = true;
                    smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
                    smtp.Credentials = new System.Net.NetworkCredential("autoimportsnoreply@gmail.com", "C0mPuTeR!ProjEct2019");
                    smtp.Send(mail);                                    
                    ViewData["info"] = "Email sent to " + email;
                }
                else
                {
                    ViewData["message"] = "Something went wrong";
                }
            }
            catch (Exception e)
            {
                ViewData["message"] = e.Message;
            }
            if (User.Identity.IsAuthenticated) {
                TempData["message"] = "Password recovery has been sent.";
                return RedirectToAction("Index", "Users");
            }
            return View("Login");
        }

        public ActionResult ChangePassword(string user, string req)
        {
            UsersOperations uo = new UsersOperations();
            try
            {
                bool a = true;
                a = uo.CheckPassReq(user, req);
                if (uo.CheckUser(user))
                {
                    if (uo.CheckPassReq(user, req))
                    {
                        ViewData["info"] = "Please choose a strong password";
                    }
                    else
                    {
                        ViewData["message"] = "Something went wrong, this could be because the user does not exist or the link you entered is incorrect. Please try again.";
                    }
                }
            }
            catch (Exception e)
            {
                ViewData["message"] = "Something went wrong! Please go back to the previous page." + e;
            }
            return View();
        }

        public ActionResult SubmitNewPassword(string username, string email, string password)
        {
            UsersOperations uo = new UsersOperations();
            if (uo.CheckUser(username))
            {
                User u = uo.GetUser(username);
                if (uo.CheckUserEmail(username, email))
                {
                    if (Regex.IsMatch(password, @"^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,15}$"))
                    {
                        uo.ChangePassword(u, new Encryption().HashString(password));
                        u.PasswordReqCode = null;
                        uo.DeletePasswordRequest(u);
                    }
                    else
                    {
                        ModelState.AddModelError("Password", "Password must be at least 8 characters, no more than 15 characters, and must include at least one upper case letter, one lower case letter, and one numeric digit.");
                        ViewData["message"] = "Password must be at least 8 characters, no more than 15 characters, and must include at least one upper case letter, one lower case letter, and one numeric digit.";
                        return View("Login");
                    }
                }
                else
                {
                    ViewData["message"] = "Email enetered doesn't match";
                }
            }
            else
            {
                ViewData["message"] = "User does not exist";
            }
            ViewData["success"] = "You have successfully changed your password";
            return View("Login");
        }

    }
}

AutoImports/AutoImports/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Common;
using BusinessLogic;
using System.Net.Mail;

namespace AutoImports.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactMessage c)
        {
            new ContactOperations().postmessage(c);
            string token = new AccountsOperations().GeneratePasswordRecoveryToken(25);

            MailMessage mail = new MailMessage();
            mail.To.Add("autoimportsnoreply@gmail.com");
            mail.From = new MailAddress("autoimportsnoreply@gmail.com");
            mail.Subject = c.Subject + " - " + c.Email;
            string body = c.Message;
            mail.Body = body;
            mail.IsBodyHtml = true;
            SmtpClient smtp = new SmtpClient();
            smtp.Host = "smtp.gmail.com";
            smtp.Port = 587;
            smtp.UseDefaultCredentials = false;
            smtp.EnableSsl = true;
            smtp.DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network;
            smtp.Credentials = new System.Net.NetworkCredential("autoimportsnoreply@gmail.com", "C0mPuTeR!ProjEct2019");
            smtp.Send(mail);
            ViewData["info"] = "Email sent to " + c.Email;
            ViewData["success"] = "Thank you for contacting us. Your message has been sent we will contact you shortly.";
            return View();
        }
    }
}

AutoImports/AutoImports/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title AutoImports</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="~/Styles/StyleSheet1.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @{
                    if (Context.User.Identity.IsAuthenticated)
                    {
                        @Html.ActionLink("Hello, " + Context.User.Identity.Name + " :)", "Index", "Home", new { area = "" }, new { @class = "navbar-brand navbarfont" })
                    }
                    else
                    {
                        @Html.ActionLink("Hello, Guest", "Index", "Home", new { area = "" }, new { @class = "navbar-brand navbarfont" })
                    }
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    @{
                        if (User.IsInRole("Admin"))
                        {
                            <li><a href="/Users/">Users</a></li>
                            <li>@Html.ActionLink("Manufacturers", "Index", "Manufacturers")</li>
                            <li><a href="~/Models/index">Models</a></li>
                            <li>@Html.ActionLink("Car Details", "Index", "Details")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Manufacturers", "Index", "Manufacturers")</li>
                            <li><a href="~/Models/index">Models</a></li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("About Us", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact Us", "Index", "Contact")</li>
                        <li>@Html.ActionLink("Sign out", "SignOut", "Accounts")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("About Us", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact Us", "Index", "Contact")</li>
                        <li>@Html.ActionLink("Login/Register", "Login", "Accounts")</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="modal fade" id="squarespaceModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
                    <h3 class="modal-title" id="lineModalLabel">Are you sure ?</h3>
                </div>
                <div class="modal-body">
                    <!-- content goes here -->
                    <div class="alert alert-info" style="margin-bottom:0;">
                        <strong>Info!</strong> You are currently logged in as @{ @User.Identity.Name}. Click Logout to register a new user.
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="btn-group" role="group" aria-label="group button">
                        <div class="btn-group" role="group">
                            <button type="button" id="logout" class="btn btn-danger" role="button">@Html.ActionLink("Log Out", "SignOut", "Accounts")</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AutoImports</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/custom.js"></script>
</body>
</html>